### PR TITLE
FEATURE: PAAS-5531 mount local EBS directly (no iSCSI)

### PR DESCRIPTION
**Pull request by tomasdubec**

### CODE REVIEW

**Comment by tomasdubec** [comment]
py27: commands succeeded
pep8: commands succeeded
congratulations :)

**Comment by martin-ducar-gd** [comment]
relates to https://github.com/gooddata/ci-infra/pull/1792

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/openstack-cinder-tox-zuul/1/ : FAILURE in 3m 22s

**Comment by martin-ducar-gd** [comment]
LGMT, the zuul requires new slaves to work and we should skip at this point but I don't have rights to merge

**Pull request merged**
